https://stepik.org/lesson/%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B8-%D0%B8-%D0%B8%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-24463/step/7?course=Python-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-%D0%B8-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5&unit=6771

Вам дано описание наследования классов исключений в следующем формате.
<имя исключения 1> : <имя исключения 2> <имя исключения 3> ... <имя исключения k>
Это означает, что исключение 1 наследуется от исключения 2, исключения 3, и т. д.

Или эквивалентно записи:

class Error1(Error2, Error3 ... ErrorK):
    pass


Антон написал код, который выглядит следующим образом.

try:
   foo()
except <имя 1>:
   print("<имя 1>")
except <имя 2>:
   print("<имя 2>")
...

Костя посмотрел на этот код и указал Антону на то, что некоторые исключения можно не ловить, так как ранее в коде будет пойман их предок. Но Антон не помнит какие исключения наследуются от каких. Помогите ему выйти из неловкого положения и напишите программу, которая будет определять обработку каких исключений можно удалить из кода.

Важное примечание:
В отличие от предыдущей задачи, типы исключений не созданы.
Создавать классы исключений также не требуется
Мы просим вас промоделировать этот процесс, и понять какие из исключений можно и не ловить, потому что мы уже ранее где-то поймали их предка.

Формат входных данных

В первой строке входных данных содержится целое число n - число классов исключений.

В следующих n строках содержится описание наследования классов. В i-й строке указано от каких классов наследуется i-й класс. Обратите внимание, что класс может ни от кого не наследоваться. Гарантируется, что класс не наследуется сам от себя (прямо или косвенно), что класс не наследуется явно от одного класса более одного раза.

В следующей строке содержится число m - количество обрабатываемых исключений.
Следующие m строк содержат имена исключений в том порядке, в каком они были написаны у Антона в коде.
Гарантируется, что никакое исключение не обрабатывается дважды.
Формат выходных данных

Выведите в отдельной строке имя каждого исключения, обработку которого можно удалить из кода, не изменив при этом поведение программы. Имена следует выводить в том же порядке, в котором они идут во входных данных.
Пример теста 1

Рассмотрим код

try:
   foo()
except ZeroDivision :
   print("ZeroDivision")
except OSError:
   print("OSError")
except ArithmeticError:
   print("ArithmeticError")
except FileNotFoundError:
   print("FileNotFoundError")


...



По условию этого теста, Костя посмотрел на этот код, и сказал Антону, что исключение FileNotFoundError можно не ловить, ведь мы уже ловим OSError -- предок FileNotFoundError

Sample Input:

4
ArithmeticError
ZeroDivisionError : ArithmeticError
OSError
FileNotFoundError : OSError
4
ZeroDivisionError
OSError
ArithmeticError
FileNotFoundError

Sample Output:

FileNotFoundError
- - -
Dmitriy K
17 часов назад
ссылка
0

Непонятно условие. Почему в приведенном примере не выводится "ZeroDivisionError", ведь в программе есть его предок - "ArithmeticError".

Подскажите!
Андрей Цепилов
15 часов назад
ссылка
0
@Dmitriy_K  ArithmeticError обрабатывается после ZeroDivisionError, следовательно ZeroDivisionError надо вывести, не нужно выводить лишь
то чьи предки обработаны на данный момент выполнения программы
- - -
для теста 4
-
5
a
b:a
c:b
d:c
e:d
5
a
d
e
b
c
- - -
Проверка
-
Sergey Bykanov
3 месяца назад
Проверяем на этих данных:
Дерево исключений:
exps = {
'a': [],
'b': [],
'c': ['a', 'b'],
'd': ['c', 'a'],
'e': ['d'],
'f': ['e'],
'g': ['f', 'a', 'd', 'e'],
'h': ['g'],
'j': ['h', 'c', 'd', 'e', 'g', 'b'],
'k': ['j', 'c', 'a']}

Входной список исключений:
q = ['d', 'b', 'a', 'h', 'f', 'k', 'c', 'j', 'g', 'e']

На выходе должно получиться:
h
f
k
c
j
g
e
-
10
a
b
c : a b
d : c a
e : d
f : e
g : f a d e
h : g
j : h c d e g b
k : j c a
10
d
b
a
h
f
k
c
j
g
e
-
h
f
k
c
j
g
e
